### ISSUE TITLE
ESB - Killing Quests

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#54] opened 2019-07-30 19:12 UTC
**Describe the bug**
Zombie Killer quest lets you kill anything and the count goes up for your quest. For example, I can kill pigs and it counts towards the quest.

**To Reproduce**
1. Start the Zombie Killer Quest.
2. Kill any mobs to the required number of kills for the quest.
3. Quest completes even tho you haven't killed any zombies.

Mobs tested - Cows, pigs, villagers.

**Expected behavior**
For the Zombie Killer Quest to require you to kill Zombies, not any mobs.

**Minecraft Version:**
 - Version 1.13.2

**Comment by Fyreheart** [comment] 2019-07-30 20:20
It could be doing this for all the "kill" quests.
Same thing is happening for the Serial Killer quest for Villagers, and Enderman Reaper quest for Endermen.

**Comment by Deathinflames** [comment] 2019-08-07 18:30
This looks to have been resolved with the latest QC update.

Please close this ticket if the issue is confirmed to be resolved.

Thanks!

**Closed as completed** 2019-08-07 21:49 UTC
Labels: Status: Bug, input needed, ready for test
