### ISSUE TITLE
ESB - Sheep Wool Drops

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#55] opened 2019-08-02 22:18 UTC
When I kill Sheep, no matter what color it's dyed, I receive Brown Wool from it.
However, if I Shear the Sheep, it gives the correct color.
I am using a Sheep Spawner.

Edit - Next day, today it's only dropping Gray Wool when I kill, no matter the color.

**Comment by Deathinflames** [comment] 2019-08-07 20:10
Using the new custom loot feature provided by the stacker plugin, i've added a small chance for different colored wool to drop. 

The Looting enchant does not effect colored wool drops and only effects mutton and white wool. 

This is temporary until the source of the issue is fixed by the developer.

**Closed as completed by Deathinflames** 2019-08-07 20:10 UTC
Labels: ready for test, Status: Completed
