### ISSUE TITLE
ESB - Essence and Quest Point Loss

### ISSUE THREAD

**Issue by DingoKing** [Deathinflames/DoD#43] opened 2019-07-10 01:33 UTC
**Describe the bug**
If you die with enough latency, the server sometimes calls the function _handleDisconnection()_ twice. This causes the player to lose their Spirit Essence in the vault, Soul Essence in the vault, and quest points (So far. Will be updated if there's anything else has been seen to be erased). Only has happened when getting kicked for 'flying' as of right now. 

**To Reproduce**
1. Have a lag issue (Like network latency, or when the particles some bosses, like Volaris or Emberclaw, lag the server)
2. Die...
3. Profit, or a lack there of. 

**Expected behavior**
Not lose Spirit Essences, Soul Essences, and Quest Points. 

**Log lines**
Not much from console saying much about it. Just these few lines. 

```
[14:37:36] [Server thread/WARN]: Septina was kicked for floating too long!
[14:37:36] [Server thread/INFO]: Septina lost connection: Flying is not enabled on this server
[14:37:36] [Server thread/WARN]: handleDisconnection() called twice
```
I think the issue is in the writing of the numbers on disconnect. 

**Minecraft Version:**
 - MC 1.13.2
 - Vanilla Launcher
 -  Optifine

**Comment by Deathinflames** [comment] 2019-07-10 07:02
Added an additional variable save for the on player kick event. Monitoring to see if this completely resolves the issue.

**Comment by Deathinflames** [comment] 2019-07-15 20:12
There still seems to be some minor QP loss however it is currently undetermined as to what the cause might be. 

Note to self: Improve QP add/remove event notifications so they can be better referenced in the logs.

**Comment by Deathinflames** [comment] 2019-08-01 21:58
A fix has been implemented for this that should protect Spirit Essence, Soul Essence, and Quest Points.

Closing this ticket. Please re-open if either of these 3 items continue to reset under various circumstances.

**Closed as completed by Deathinflames** 2019-08-01 21:58 UTC
Labels: Status: Bug, ready for test, Status: Monitoring
